export const DEFAULT_SITE_CONFIG = {
  avatarUrl: "/placeholder.jpg",
  name: "Muhammad Usman",
  title: "Full-Stack Developer",
  bio: "Dedicated Full-Stack Developer with a focus on the MERN stack — MongoDB, Express.js, React, and Node.js.",
  resumeUrl: "https://drive.google.com/file/d/1L8iT_FWQeu5zaE9CWjt7kEoik7iMzb51/view?usp=sharing",
  location: "Faisalabad, Pakistan • Working with Global Clients",
  available: true,
  availableText: "Available for Freelance & Full-Stack Roles",
  typingRoles: [
    "Full-Stack Developer",
    "MERN Stack Specialist",
    "Fiverr Level-1 Freelancer",
    "UI/UX Engineering Enthusiast",
    "Next.js & React Architect",
  ],
  email: "usmankousar772@gmail.com",
  whatsapp: "+92 328 6596772",
  whatsappUrl: "https://wa.me/923286596772",
  github: "https://github.com/mani78979",
  linkedin: "http://www.linkedin.com/in/musman78",
  fiverrUrl: "https://www.fiverr.com/musman079",
  fiverrRating: "5.0",
  fiverrLevel: "Level 1",
  aboutHeading: "About Me",
  aboutParagraph1: "I'm a dedicated Full-Stack MERN Engineer who specializes in designing scalable, secure web architectures and highly-responsive user interfaces.",
  aboutParagraph2: "From developing complex multi-tier full stack applications to optimizing REST APIs and crafting Figma-accurate React/Next.js interfaces, I take pride in delivering software that performs flawlessly.",
  aboutParagraph3: "As a Level-1 freelancer on Fiverr with a consistent 5.0★ rating, I have successfully collaborated with businesses and founders across the USA, UK, Germany, and beyond.",
  aboutBadges: [
    { label: "MERN Architecture", color: "#f59e0b" },
    { label: "Figma to Pixel-Code", color: "#06b6d4" },
    { label: "REST API & JWT Auth", color: "#10b981" },
    { label: "Fiverr Level-1 Pro", color: "#ec4899" },
  ],
  stats: [
    { label: "Projects Built", num: 12, suffix: "+", color: "#f59e0b", isFloat: false },
    { label: "Happy Clients", num: 15, suffix: "+", color: "#0ea5e9", isFloat: false },
    { label: "Fiverr Rating", num: 5.0, suffix: "★", color: "#fbbf24", isFloat: true },
    { label: "On-Time Delivery", num: 100, suffix: "%", color: "#10b981", isFloat: false },
  ],
  journey: [
    {
      year: "2024 — Present",
      title: "Freelance Full-Stack Developer",
      subtitle: "Fiverr Level-1 Seller (5.0★ Rating)",
      description: "Delivering end-to-end full-stack web applications for global clients with 100% on-time completion, specializing in MERN stack and Next.js.",
      badge: "Active",
      color: "#f59e0b",
    },
    {
      year: "2023 — 2024",
      title: "Full-Stack Web Specialization",
      subtitle: "MERN Stack & Next.js Ecosystem",
      description: "Deep dive into scalable RESTful API design, JWT authentication, MongoDB optimization, and modern React 19 / Next.js architecture.",
      badge: "Milestone",
      color: "#0ea5e9",
    },
    {
      year: "2022 — 2023",
      title: "Mobile & Machine Learning Research",
      subtitle: "Satellite Imagery & Urban Sprawl Analysis",
      description: "Engineered cross-platform mobile apps using Flutter and integrated offline-capable TensorFlow Lite machine learning models for satellite image analysis.",
      badge: "Research",
      color: "#10b981",
    },
    {
      year: "2021 — 2025",
      title: "BS Computer Science",
      subtitle: "Undergraduate Degree",
      description: "Comprehensive computer science education focusing on Data Structures, Algorithms, Database Management Systems, and Software Architecture.",
      badge: "Degree",
      color: "#8b5cf6",
    },
  ],
  estimatorRates: {
    mern: 250,
    frontend: 180,
    api: 140,
    mobile: 290,
    auth: 45,
    db: 60,
    payment: 80,
    admin: 95,
    realtime: 75,
    seo: 40,
  },
  footerBio: "Full-Stack MERN Developer • Available for Global Freelance Work",
  copyrightText: "Muhammad Usman. Built with Next.js 15 & Tailwind CSS.",
};
